### ISSUE TITLE
Bug with user options

### ISSUE THREAD

**Issue by Barbercrew3809** [VortexChelmsford/VortexDigitalControl#4]
When the mouse hits the hitbox of the welcome user the lock system highlights and when you click it asks to lock or not

[VortexLog.log](https://github.com/VortexChelmsford/VortexDigitalControl/files/4932659/VortexLog.log)

**Comment by Barbercrew3809** [comment]
max fixed the issue regarding this bug

**Comment by VortexChelmsford** [comment]
Hello, **Brandon**

We're glad to hear that @maxplayle04 has fixed this issue. 

_Thank you for reporting this issue._
James Burdock, Level 2 Development and Engineering Officer, Vortex Chelmsford Dev Team
